### ISSUE TITLE
"Cannot read property 'LandTrendr' of undefined"

### ISSUE THREAD

**Issue by MartinBrandt** [eMapR/LT-GEE#1]
Dear Landtrendr team,

great thanks for putting this piece together, I'm sure the combination of Landtrendr and GEE will be a big leap forward in science! 

There seems however to be an error, when trying the examples (on different systems with different settings) this error pops up: "Cannot read property 'LandTrendr' of undefined"...

all the best,
Martin

**Comment by jdbcode** [comment]
Martin,

Thanks for your interest. The LT-GEE function has not been made public yet.
At this point you need developer permission to run it. It should be
released publicly by the end of next week.

I'll email you when it is ready. It should also be announced on the GEE
help forum:
https://groups.google.com/forum/#!forum/google-earth-engine-developers

Best,

Justin


Justin Braaten
Faculty Research Assistant (Remote from Santa Cruz, CA)
College of Earth, Ocean, and Atmospheric Sciences
Oregon State University

**Comment by MartinBrandt** [comment]
OK, thanks for the rapid answer, looking forward to try it next week!

best regards,

Martin

**Comment by jdbcode** [comment]
:)

We'll look forward to your feedback!


Justin Braaten
Faculty Research Assistant (Remote from Santa Cruz, CA)
College of Earth, Ocean, and Atmospheric Sciences
Oregon State University

**Comment by jdbcode** [comment]
The LT-GEE function has not been made public yet.
At this point you need developer permission to run it. It should be
released publicly by the end of next week (May 11).
