### ISSUE TITLE
Error in the 'reduceToSingeImageMockFunction'

### ISSUE THREAD

**Issue by LiliGuimaraes** [eMapR/LT-GEE#3]
I've been trying to use the 'reduceToSingeImageMockFunction' follow up the LT-GEE Guide and this doesn't seem to work, applying the basic running LT-GEE script .

**Comment by jdbcode** [comment]
That isn't an existing function. It is pseudo code - a mock function name used as a placeholder for a real function that you define to reduce an annual set of images to a single image. As an example, you can use `.reduce(ee.Reducer.mean())` on an annual ee.ImageCollection.
