### ISSUE TITLE
ROY coefficients

### ISSUE THREAD

**Issue by lucas-johnson** [eMapR/LT-GEE#30]
Hello - thanks for an amazing set of tools and documentation! This has all been so helpful.

I noticed the warning about the use of collection 2, and the decision to not use the ROY coefficients for scaling.  Looking a bit deeper I noticed the following note:
https://github.com/eMapR/LT-GEE/blob/5d70f99bf81a87401fe2520258cb9426884743ae/LandTrendr.js#L107

Could you provide any more insight into those use cases around the world? Maybe some studies? Thank you!

**Comment by colettembrown** [comment]
Hello! Following up to see if anyone has a workaround for the Collection 2 Landsat data and harmonizing without the Roy coefficients, or what is causing the issue with these coefficients? Thank you for any tips / thoughts!

**Comment by clarype** [comment]
I am tolled, they didn't make a big difference with the implementation of Collection 2. My colleague conducted an unpublished analysis on many locations around the world, and did not find a large difference between the corrected Collection 1 and the uncorrected Collection 2.  I will see if I can get more info.

**Comment by colettembrown** [comment]
Can you send me the unpublished analysis? Or potentially how they
determined C1 and C2 could be harmonized in the same way? This sounds like
great news.

**Comment by jdbcode** [comment]
This might help: https://developers.google.com/earth-engine/faq#is_cross-sensor_landsat_surface_reflectance_harmonization_needed
