### ISSUE TITLE
Adding EVI to available vegetation indices

### ISSUE THREAD

**Issue by kharris91** [eMapR/LT-GEE#6]
Thank you for this very useful algorithm.  I have been using the Zonal Time Series Plotter to create NDVI time series, but recent work has shown that EVI may be a more accurate index when it comes to wetland vegetation.  EVI (for Landsat 4-7) is calculated as: 2.5 * ((Band 4 – Band 3) / (Band 4 + 6 * Band 3 – 7.5 * Band 1 + 1)).  Is this a feature that could be added to LandTrendr.js in order for the index to be available for future LandTrendr scripts?

**Comment by jdbcode** [comment]
Great idea!
In progress.

**Comment by jdbcode** [comment]
It has been added and the UI Apps mentioned [here](https://emapr.github.io/LT-GEE/ui-applications.html) have been republished. I've tested it a little and it seems to be working fine. Note that it is scaled by 1000. Please give it a try and if it is as expected please close this issue or let me know if something seems wrong.

**Comment by kharris91** [comment]
> It has been added and the UI Apps mentioned [here](https://emapr.github.io/LT-GEE/ui-applications.html) have been republished. I've tested it a little and it seems to be working fine. Note that it is scaled by 1000. Please give it a try and if it is as expected please close this issue or let me know if something seems wrong.

Thanks @jdbcode for the quick turnaround, I've been testing it this morning in the Zonal Time Series Plotter and Greatest Disturbance Mapper, and it's been working well for me.  This will be a very useful tool for wetland vegetation change detection, I'm looking forward to utilizing it!

**Comment by jdbcode** [comment]
Glad to hear it - thanks for testing!
