### ISSUE TITLE
Exporting shows nothing

### ISSUE THREAD

**Issue by bkomaki** [eMapR/LT-GEE#9]
Hi, I have tested this code, but I got nothing;  
as it showed NoneType data error!
ltVertStack = getLTvertStack(lt.select(["LandTrendr"])).toShort()

drive = ee.batch.Export.image.toDrive(
            image = ltVertStack,
            description = "ltVertStack_test_to_drive", 
            folder = 'lt_gee_py_test', 
            fileNamePrefix = 'ltVertStack_test',
            region = [[-123.98757934570312,47.49679221520181],[-123.90655517578125,47.49586436835716],[-123.90449523925781,47.55243302404593],[-123.98551940917969,47.553359870859]], 
            scale = 30
        )
drive.start()

**Comment by jdbcode** [comment]
Hi @bkomaki, sorry for the slow reply. I realize that you may have moved on from the problem. However, I'm willing to take a look if it is still an issue for you and you can supply a reproducible [JavaScript Code Editor script link](https://developers.google.com/earth-engine/guides/playground#get-link) or a shared [Colab notebook](https://colab.sandbox.google.com/github/google/earthengine-api/blob/master/python/examples/ipynb/ee-api-colab-setup.ipynb).

I'm going to close this issue for now, assuming that my reply is too late. Please reopen and provide a reproduceable example if you would like me to investigate.
